apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
  labels:
    tier: frontend
    app: nginx
spec:
  selector:
    matchLabels:
      env: latest
  replicas: 3
  template:
    metadata:
      name: myapp
      labels:
        env: latest
    spec:
      containers:
        - name: nginx
          image: nginx
    
    
